let str = 'This are four words'
console.log(str)
let strObject = new String('This are four worlds')
console.log(typeof str)
console.log(typeof strObject)
console.log(strObject)
console.log(str == strObject)
let stringArray = str.split(' ')
console.log(stringArray)
console.log(stringArray.length)
let stringArray2 = strObject.split(' ')
console.log(stringArray2)
console.log(stringArray2.length)
console.log(str.includes('are'))
console.log(str.toUpperCase())
console.log(strObject.toLowerCase())

let word = str.split(' ')
word.forEach(i =>{
    console.log(i)
})